language: ruby
bundler_args: --without development
script:
- bundle exec rake lint
- bundle exec rake validate
- bundle exec rake spec SPEC_OPTS='--format documentation'
- sh tests/acceptance.sh
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3477acef6dd93b015c9b
    on_success: change
    on_failure: always
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
before_install:
- openssl aes-256-cbc -K $encrypted_aa8913b81047_key -iv $encrypted_aa8913b81047_iv
  -in secrets.tar.enc -out secrets.tar -d
