---
env:
- PUPPET_VERSION=2.7.23
- PUPPET_VERSION=3.3.2
notifications:
email: false
rvm:
- 1.9.3
- 1.8.7
matrix:
  allow_failures:
  - env: PUPPET_VERSION=2.7.23
language: ruby
before_script: "gem install --no-ri --no-rdoc bundler"
script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'
gemfile: Gemfile
